### ISSUE TITLE
Location Selector > Pathbar style

### ISSUE THREAD

**Issue by flocculant** [andreldm/thunar#27]
Breadcrumbs - rectangular - some rounded corners, some not - totally different from the 'sensibly' shaped arrow type breadcrumb in gtk2

Appears to be a 'final' breadcrumb added which doesn't seem to actually be part of the path. Click on this 'extra' and pathbar reverts to toolbar style. Move to somewhere else in the path and reverts to pathbar again.

![pathbar](https://cloud.githubusercontent.com/assets/16842846/26211987/fc97250e-3beb-11e7-884a-64582870febe.png)
![pathbargtk2](https://cloud.githubusercontent.com/assets/16842846/26211988/fcac7850-3beb-11e7-9594-d0c1cc8a991d.png)

**Comment by alexxcons** [comment]
clicking on the 'final' breadcrumb gives:
(thunar:24544): Gtk-CRITICAL **: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

When pathbar is build, the following is reported:
(thunar:24544): Gtk-WARNING **: Allocating size to GtkButton 0x559d46f2bdc0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

**Comment by alexxcons** [comment]
Ok, there are different options:

1. Disable the feature  "pathbar reverts to toolbar style" when clicked on 'final' breadcrumb. --> Easy to fix ... I could do a pull request by now.
2. Remove the whole 'final' breadcrumb. Basically as well easy, but last element of path needs some graphical fix, to be good-looking again.
3. Revert the changes done by Jonas ( 3ba177c, 9fec059 and 8bb1a69, thanks for investigation Andreldm ) in order to get the old style back. Not that easy. It's not straight forward.  On the first try I got many conflicts even on first revert.  I could take a try to resolve all conflicts and see if it compiles. Probably the old stuff than needs to be moved to gtk3.

**Comment by andreldm** [comment]
Hmm, I don't see anything wrong with the final breadcrumb, "it's a feature, not a bug" 😉
Actually I kinda like it. Is it a problem for you guys?

@flocculant, you mentioned that some breadcrumbs are rounded corners and some aren't, to me only the first and last ones have rounded corners, and it seems to be intentional. Is is really necessary to maintain the arrow buttons? Maybe this can be achieved with a bit of css magic.

So, IMHO, what's left to do is to fix the CRITICAL and WARNING messages (I'll look into that).

**Comment by alexxcons** [comment]
For me it is fine to keep the feature. I admit that it simplifies life of pathbar-users if a path needs to be copied / pasted .. actually now that I started to use the pathbar, I start to like it  ;)

However currently the feature is a bit of a "secret" ... it is not clear by hearth that one can edit the path like that directly. What about making it more obvious ? E.g. by showing some icon at the very right end of the final breadcrumb ? 
E.g:
/usr/share/icons/gnome/32x32/apps/xfce-edit.png : ![xfce-edit](https://cloud.githubusercontent.com/assets/2205293/26532688/42105eba-4408-11e7-88ad-bec1cc71a63e.png)
/usr/share/icons/HighContrast/32x32/stock/gtk-edit.png: ![gtk-edit](https://cloud.githubusercontent.com/assets/2205293/26532693/67ffd34e-4408-11e7-9528-fe2a878bc3d8.png)

The second one would be even better from my POV, since it fits to the other used icons.  What do you think ?

If you like, I as well could take care for the CRITICAL and the WARNING

**Comment by andreldm** [comment]
@cron-job the icon was a nice idea, done in 07b6bdd.
I also fixed the warning in 90059d8, but I wasn't able to find out what's causing the critical message, please take a look at this.

**Comment by alexxcons** [comment]
Wow, thanks, that was a fast fix  :smile:  ... ok, I will test the commit & search for the CRITICAL

**Comment by alexxcons** [comment]
@andreldm Good job ! 
Regarding the CRITICAL (or the 3 criticals) , they are emitted by the following gtk_widget_destroy: https://github.com/andreldm/thunar/blob/90059d8278a13c6a6969e1b3cf605b8fd5ab4adb/thunar/thunar-location-bar.c#L261-L262

Possibly some references to the destroyed object/sub-object still exist ... need to further investigate.

**Comment by andreldm** [comment]
@cron-job yeah, I forgot to mention that I reached this suspect part of the code yesterday, sorry. Well, you're on the right track I guess, the trouble now is to figure out how to make this pathbar switching cleanly.

**Comment by flocculant** [comment]
@andreldm re corners - yea I see what you see there. As far as 'arrow' or 'box' I have no real preference was just commenting on the difference. 

@cron-job re Icon - yea - that was a good idea :)

**Comment by cron-job** [comment]
Probably CRIT comes from `thunar_location_buttons_finalize`. No time to take a look inside, need to go to work now :cry: , will check later.   Here the methods called before CRIT:

thunar_location_buttons_draw
thunar_location_buttons_draw
thunar_location_buttons_draw
thunar_location_buttons_unmap
thunar_location_buttons_remove
thunar_location_buttons_remove_1
thunar_location_buttons_remove
thunar_location_buttons_remove_1
thunar_location_buttons_remove
thunar_location_buttons_remove_1
thunar_location_buttons_remove
thunar_location_buttons_remove_1
thunar_location_buttons_remove
thunar_location_buttons_remove_1
thunar_location_buttons_remove
thunar_location_buttons_remove_1
thunar_location_buttons_remove
thunar_location_buttons_remove_1
thunar_location_buttons_finalize

(thunar:3958): Gtk-CRITICAL **: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(thunar:3958): Gtk-CRITICAL **: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(thunar:3958): Gtk-CRITICAL **: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

**Comment by alexxcons** [comment]
My quess would be that the CRITICAL  comes from the fact that the widget " ThunarLocationButtons->filler_widget" destroys itself in it's own callback by [emitting the signal "entry-requested".](https://github.com/andreldm/thunar/blob/gtk3/thunar/thunar-location-buttons.c#L251). Maybe you know if self-destroy is "legal" in gtk3 ?

Probably the gtk3 callback-caller want to do some post-callback actions on the callback owner, which fail if the owner does not exist any more.

A possible fix could be to just unlink the location-butons/entry from their parent-widget instead of destroying/re-creating them ... I'll further investigate.

**Comment by alexxcons** [comment]
Ok, it works without CRIT to just keep references to both(location-buttons and entry) in location-bar and just use gtk_container_remove / gtk_container_add to toggle between both. I think this anyhow is the better approach.

However doing so has some design-consequences, e.g. for member "current_directory" ... need some more time to prepare a proper patch .. hope I will be able to work on it this weekend.

**Comment by alexxcons** [comment]
@andreldm 
Finally done: #35  :smile:    .... please take a look and let me know if it is fine like that!

**Comment by andreldm** [comment]
This is settled in #35, which is almost ready to be merged.
